### ISSUE TITLE
Track down why CI is failing / very intermittent

### ISSUE THREAD

**Issue by fitzgen** [fitzgen/preduce#14]
Something to do with pipes and child processes I expect

**Comment by fitzgen** [comment]
Here is the tail of a log of a typical CI failure:

```
+../reducers/balanced-curly.py fixtures/nested-classes.cpp
++mktemp
+tmp=/home/travis/build/fitzgen/preduce/tests/tmp.7NsxUV2UQw
+echo /home/travis/build/fitzgen/preduce/tests/tmp.7NsxUV2UQw
+read -t 10 empty
+[[ '' != '' ]]
+diff -U8 expectations/balanced-curly-0 /home/travis/build/fitzgen/preduce/tests/tmp.7NsxUV2UQw
+for expected in '$@'
++mktemp
+tmp=/home/travis/build/fitzgen/preduce/tests/tmp.8iJX6hK4Gv
+echo /home/travis/build/fitzgen/preduce/tests/tmp.8iJX6hK4Gv
+read -t 10 empty
Traceback (most recent call last):
  File "../reducers/balanced-curly.py", line 15, in <module>
    main()
  File "../reducers/balanced-curly.py", line 12, in main
    balanced_reducer(sys.argv[1], BalancedBracketFinder.curly)
  File "/home/travis/build/fitzgen/preduce/reducers/reducer_utils.py", line 296, in balanced_reducer
    sys.stdout.flush()
IOError: [Errno 32] Broken pipe
test tests_sh ... FAILED
```

**Comment by fitzgen** [comment]
Rewrote the tests in Rust instead of bash and it all works now.
